# Cross compiled on Linux. It is possible to build natively.

VALAC=valac
LOPTS=-X -lm
CC=i586-mingw32msvc-gcc
OPTS=-X -O2 --target-glib=2.36 --thread --cc=$(CC)

export PKG_CONFIG_PATH=/opt/misc/gtk3-win32/lib/pkgconfig

CLISRC=	ublox.vapi ublox-cli.vala ublox-io.vala mwplog.vala cserial.c init_signals.c
ublox-cli.exe: $(CLISRC)
	$(VALAC) $(OPTS)  --pkg posix --pkg gio-2.0 --pkg posix \
		$(CLISRC) -o ublox-cli.exe

clean:
	rm -f ublox-cli.exe
