# MIT licence
STATES = %w/NAV_STATE_UNDEFINED #0
  NAV_STATE_IDLE 	#1
  NAV_STATE_ALTHOLD_INITIALIZE #2
  NAV_STATE_ALTHOLD_IN_PROGRESS #3
  NAV_STATE_POSHOLD_2D_INITIALIZE #4
  NAV_STATE_POSHOLD_2D_IN_PROGRESS #5
  NAV_STATE_POSHOLD_3D_INITIALIZE #6
  NAV_STATE_POSHOLD_3D_IN_PROGRESS #7
  NAV_STATE_RTH_INITIALIZE #8
  NAV_STATE_RTH_2D_INITIALIZE #9
  NAV_STATE_RTH_2D_HEAD_HOME #10
  NAV_STATE_RTH_2D_GPS_FAILING #11
  NAV_STATE_RTH_2D_FINISHING #12
  NAV_STATE_RTH_2D_FINISHED #13
  NAV_STATE_RTH_3D_INITIALIZE # 14
  NAV_STATE_RTH_3D_CLIMB_TO_SAFE_ALT #15
  NAV_STATE_RTH_3D_HEAD_HOME #16
  NAV_STATE_RTH_3D_GPS_FAILING #17
  NAV_STATE_RTH_3D_HOVER_PRIOR_TO_LANDING #18
  NAV_STATE_RTH_3D_LANDING #19
  NAV_STATE_RTH_3D_FINISHING #20
  NAV_STATE_RTH_3D_FINISHED #21
  NAV_STATE_WAYPOINT_INITIALIZE #22
  NAV_STATE_WAYPOINT_PRE_ACTION #23
  NAV_STATE_WAYPOINT_IN_PROGRESS #24
  NAV_STATE_WAYPOINT_REACHED #25
  NAV_STATE_WAYPOINT_NEXT #26
  NAV_STATE_WAYPOINT_FINISHED #27
  NAV_STATE_WAYPOINT_RTH_LAND #28
  NAV_STATE_EMERGENCY_LANDING_INITIALIZE #29
  NAV_STATE_EMERGENCY_LANDING_IN_PROGRESS #30
  NAV_STATE_EMERGENCY_LANDING_FINISHED #31
  NAV_STATE_LAUNCH_INITIALIZ #32
  NAV_STATE_LAUNCH_WAIT #33
  NAV_STATE_LAUNCH_MOTOR_DELAY #34
  NAV_STATE_LAUNCH_IN_PROGRESS #35
/
