VALAC=valac
LOPTS=-X -lm
CC=i586-mingw32msvc-gcc
WOPTS=-X -O2 --target-glib=2.36 --thread --cc=$(CC) -X -L.

export PKG_CONFIG_PATH=/opt/misc/gtk3-win32/lib/pkgconfig

CMN=../../common

CLISRC=	ublox.vapi ublox-cli-w32.vala ublox-io.vala $(CMN)/mwplog.vala cserial.c
ublox-cli.exe: $(CLISRC)
	$(VALAC) $(WOPTS)  --pkg posix --pkg gio-2.0 --pkg posix \
		$(CLISRC) -o ublox-cli.exe
