/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: readsb.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "readsb.pb-c.h"
void   aircraft_meta__nav_modes__init
                     (AircraftMeta__NavModes         *message)
{
  static const AircraftMeta__NavModes init_value = AIRCRAFT_META__NAV_MODES__INIT;
  *message = init_value;
}
void   aircraft_meta__valid_source__init
                     (AircraftMeta__ValidSource         *message)
{
  static const AircraftMeta__ValidSource init_value = AIRCRAFT_META__VALID_SOURCE__INIT;
  *message = init_value;
}
void   aircraft_meta__init
                     (AircraftMeta         *message)
{
  static const AircraftMeta init_value = AIRCRAFT_META__INIT;
  *message = init_value;
}
size_t aircraft_meta__get_packed_size
                     (const AircraftMeta *message)
{
  assert(message->base.descriptor == &aircraft_meta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aircraft_meta__pack
                     (const AircraftMeta *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aircraft_meta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aircraft_meta__pack_to_buffer
                     (const AircraftMeta *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aircraft_meta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AircraftMeta *
       aircraft_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AircraftMeta *)
     protobuf_c_message_unpack (&aircraft_meta__descriptor,
                                allocator, len, data);
}
void   aircraft_meta__free_unpacked
                     (AircraftMeta *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aircraft_meta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aircraft_history__init
                     (AircraftHistory         *message)
{
  static const AircraftHistory init_value = AIRCRAFT_HISTORY__INIT;
  *message = init_value;
}
size_t aircraft_history__get_packed_size
                     (const AircraftHistory *message)
{
  assert(message->base.descriptor == &aircraft_history__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aircraft_history__pack
                     (const AircraftHistory *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aircraft_history__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aircraft_history__pack_to_buffer
                     (const AircraftHistory *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aircraft_history__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AircraftHistory *
       aircraft_history__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AircraftHistory *)
     protobuf_c_message_unpack (&aircraft_history__descriptor,
                                allocator, len, data);
}
void   aircraft_history__free_unpacked
                     (AircraftHistory *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aircraft_history__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aircrafts_update__init
                     (AircraftsUpdate         *message)
{
  static const AircraftsUpdate init_value = AIRCRAFTS_UPDATE__INIT;
  *message = init_value;
}
size_t aircrafts_update__get_packed_size
                     (const AircraftsUpdate *message)
{
  assert(message->base.descriptor == &aircrafts_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aircrafts_update__pack
                     (const AircraftsUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aircrafts_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aircrafts_update__pack_to_buffer
                     (const AircraftsUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aircrafts_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AircraftsUpdate *
       aircrafts_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AircraftsUpdate *)
     protobuf_c_message_unpack (&aircrafts_update__descriptor,
                                allocator, len, data);
}
void   aircrafts_update__free_unpacked
                     (AircraftsUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aircrafts_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   receiver__init
                     (Receiver         *message)
{
  static const Receiver init_value = RECEIVER__INIT;
  *message = init_value;
}
size_t receiver__get_packed_size
                     (const Receiver *message)
{
  assert(message->base.descriptor == &receiver__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t receiver__pack
                     (const Receiver *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &receiver__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t receiver__pack_to_buffer
                     (const Receiver *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &receiver__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Receiver *
       receiver__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Receiver *)
     protobuf_c_message_unpack (&receiver__descriptor,
                                allocator, len, data);
}
void   receiver__free_unpacked
                     (Receiver *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &receiver__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   statistic_entry__init
                     (StatisticEntry         *message)
{
  static const StatisticEntry init_value = STATISTIC_ENTRY__INIT;
  *message = init_value;
}
size_t statistic_entry__get_packed_size
                     (const StatisticEntry *message)
{
  assert(message->base.descriptor == &statistic_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t statistic_entry__pack
                     (const StatisticEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &statistic_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t statistic_entry__pack_to_buffer
                     (const StatisticEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &statistic_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatisticEntry *
       statistic_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatisticEntry *)
     protobuf_c_message_unpack (&statistic_entry__descriptor,
                                allocator, len, data);
}
void   statistic_entry__free_unpacked
                     (StatisticEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &statistic_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   statistics__polar_range_entry__init
                     (Statistics__PolarRangeEntry         *message)
{
  static const Statistics__PolarRangeEntry init_value = STATISTICS__POLAR_RANGE_ENTRY__INIT;
  *message = init_value;
}
void   statistics__init
                     (Statistics         *message)
{
  static const Statistics init_value = STATISTICS__INIT;
  *message = init_value;
}
size_t statistics__get_packed_size
                     (const Statistics *message)
{
  assert(message->base.descriptor == &statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t statistics__pack
                     (const Statistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t statistics__pack_to_buffer
                     (const Statistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Statistics *
       statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Statistics *)
     protobuf_c_message_unpack (&statistics__descriptor,
                                allocator, len, data);
}
void   statistics__free_unpacked
                     (Statistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor aircraft_meta__nav_modes__field_descriptors[6] =
{
  {
    "autopilot",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__NavModes, autopilot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vnav",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__NavModes, vnav),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "althold",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__NavModes, althold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "approach",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__NavModes, approach),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lnav",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__NavModes, lnav),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcas",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__NavModes, tcas),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aircraft_meta__nav_modes__field_indices_by_name[] = {
  2,   /* field[2] = althold */
  3,   /* field[3] = approach */
  0,   /* field[0] = autopilot */
  4,   /* field[4] = lnav */
  5,   /* field[5] = tcas */
  1,   /* field[1] = vnav */
};
static const ProtobufCIntRange aircraft_meta__nav_modes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor aircraft_meta__nav_modes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AircraftMeta.NavModes",
  "NavModes",
  "AircraftMeta__NavModes",
  "",
  sizeof(AircraftMeta__NavModes),
  6,
  aircraft_meta__nav_modes__field_descriptors,
  aircraft_meta__nav_modes__field_indices_by_name,
  1,  aircraft_meta__nav_modes__number_ranges,
  (ProtobufCMessageInit) aircraft_meta__nav_modes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aircraft_meta__valid_source__field_descriptors[33] =
{
  {
    "callsign",
    100,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, callsign),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    101,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alt_geom",
    102,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, alt_geom),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gs",
    103,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, gs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ias",
    104,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, ias),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tas",
    105,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, tas),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mach",
    106,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, mach),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track",
    107,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, track),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track_rate",
    108,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, track_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roll",
    109,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mag_heading",
    110,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, mag_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "true_heading",
    111,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, true_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baro_rate",
    112,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, baro_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geom_rate",
    113,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, geom_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "squawk",
    114,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, squawk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "emergency",
    115,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, emergency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_qnh",
    116,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nav_qnh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_altitude_mcp",
    117,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nav_altitude_mcp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_altitude_fms",
    118,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nav_altitude_fms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_heading",
    119,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nav_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_modes",
    120,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nav_modes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    121,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon",
    122,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, lon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nic",
    123,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rc",
    124,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, rc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nic_baro",
    125,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nic_baro),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nac_p",
    126,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nac_p),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nac_v",
    127,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, nac_v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sil",
    128,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, sil),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sil_type",
    129,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, sil_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gva",
    130,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, gva),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sda",
    131,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, sda),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wind",
    132,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta__ValidSource, wind),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aircraft_meta__valid_source__field_indices_by_name[] = {
  2,   /* field[2] = alt_geom */
  1,   /* field[1] = altitude */
  12,   /* field[12] = baro_rate */
  0,   /* field[0] = callsign */
  15,   /* field[15] = emergency */
  13,   /* field[13] = geom_rate */
  3,   /* field[3] = gs */
  30,   /* field[30] = gva */
  4,   /* field[4] = ias */
  21,   /* field[21] = lat */
  22,   /* field[22] = lon */
  6,   /* field[6] = mach */
  10,   /* field[10] = mag_heading */
  26,   /* field[26] = nac_p */
  27,   /* field[27] = nac_v */
  18,   /* field[18] = nav_altitude_fms */
  17,   /* field[17] = nav_altitude_mcp */
  19,   /* field[19] = nav_heading */
  20,   /* field[20] = nav_modes */
  16,   /* field[16] = nav_qnh */
  23,   /* field[23] = nic */
  25,   /* field[25] = nic_baro */
  24,   /* field[24] = rc */
  9,   /* field[9] = roll */
  31,   /* field[31] = sda */
  28,   /* field[28] = sil */
  29,   /* field[29] = sil_type */
  14,   /* field[14] = squawk */
  5,   /* field[5] = tas */
  7,   /* field[7] = track */
  8,   /* field[8] = track_rate */
  11,   /* field[11] = true_heading */
  32,   /* field[32] = wind */
};
static const ProtobufCIntRange aircraft_meta__valid_source__number_ranges[1 + 1] =
{
  { 100, 0 },
  { 0, 33 }
};
const ProtobufCMessageDescriptor aircraft_meta__valid_source__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AircraftMeta.ValidSource",
  "ValidSource",
  "AircraftMeta__ValidSource",
  "",
  sizeof(AircraftMeta__ValidSource),
  33,
  aircraft_meta__valid_source__field_descriptors,
  aircraft_meta__valid_source__field_indices_by_name,
  1,  aircraft_meta__valid_source__number_ranges,
  (ProtobufCMessageInit) aircraft_meta__valid_source__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue aircraft_meta__air_ground__enum_values_by_number[4] =
{
  { "AG_INVALID", "AIRCRAFT_META__AIR_GROUND__AG_INVALID", 0 },
  { "AG_GROUND", "AIRCRAFT_META__AIR_GROUND__AG_GROUND", 1 },
  { "AG_AIRBORNE", "AIRCRAFT_META__AIR_GROUND__AG_AIRBORNE", 2 },
  { "AG_UNCERTAIN", "AIRCRAFT_META__AIR_GROUND__AG_UNCERTAIN", 3 },
};
static const ProtobufCIntRange aircraft_meta__air_ground__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex aircraft_meta__air_ground__enum_values_by_name[4] =
{
  { "AG_AIRBORNE", 2 },
  { "AG_GROUND", 1 },
  { "AG_INVALID", 0 },
  { "AG_UNCERTAIN", 3 },
};
const ProtobufCEnumDescriptor aircraft_meta__air_ground__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AircraftMeta.AirGround",
  "AirGround",
  "AircraftMeta__AirGround",
  "",
  4,
  aircraft_meta__air_ground__enum_values_by_number,
  4,
  aircraft_meta__air_ground__enum_values_by_name,
  1,
  aircraft_meta__air_ground__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aircraft_meta__addr_type__enum_values_by_number[10] =
{
  { "ADDR_ADSB_ICAO", "AIRCRAFT_META__ADDR_TYPE__ADDR_ADSB_ICAO", 0 },
  { "ADDR_ADSB_ICAO_NT", "AIRCRAFT_META__ADDR_TYPE__ADDR_ADSB_ICAO_NT", 1 },
  { "ADDR_ADSR_ICAO", "AIRCRAFT_META__ADDR_TYPE__ADDR_ADSR_ICAO", 2 },
  { "ADDR_TISB_ICAO", "AIRCRAFT_META__ADDR_TYPE__ADDR_TISB_ICAO", 3 },
  { "ADDR_ADSB_OTHER", "AIRCRAFT_META__ADDR_TYPE__ADDR_ADSB_OTHER", 4 },
  { "ADDR_ADSR_OTHER", "AIRCRAFT_META__ADDR_TYPE__ADDR_ADSR_OTHER", 5 },
  { "ADDR_TISB_TRACKFILE", "AIRCRAFT_META__ADDR_TYPE__ADDR_TISB_TRACKFILE", 6 },
  { "ADDR_TISB_OTHER", "AIRCRAFT_META__ADDR_TYPE__ADDR_TISB_OTHER", 7 },
  { "ADDR_MODE_A", "AIRCRAFT_META__ADDR_TYPE__ADDR_MODE_A", 8 },
  { "ADDR_UNKNOWN", "AIRCRAFT_META__ADDR_TYPE__ADDR_UNKNOWN", 9 },
};
static const ProtobufCIntRange aircraft_meta__addr_type__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex aircraft_meta__addr_type__enum_values_by_name[10] =
{
  { "ADDR_ADSB_ICAO", 0 },
  { "ADDR_ADSB_ICAO_NT", 1 },
  { "ADDR_ADSB_OTHER", 4 },
  { "ADDR_ADSR_ICAO", 2 },
  { "ADDR_ADSR_OTHER", 5 },
  { "ADDR_MODE_A", 8 },
  { "ADDR_TISB_ICAO", 3 },
  { "ADDR_TISB_OTHER", 7 },
  { "ADDR_TISB_TRACKFILE", 6 },
  { "ADDR_UNKNOWN", 9 },
};
const ProtobufCEnumDescriptor aircraft_meta__addr_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AircraftMeta.AddrType",
  "AddrType",
  "AircraftMeta__AddrType",
  "",
  10,
  aircraft_meta__addr_type__enum_values_by_number,
  10,
  aircraft_meta__addr_type__enum_values_by_name,
  1,
  aircraft_meta__addr_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aircraft_meta__emergency__enum_values_by_number[8] =
{
  { "EMERGENCY_NONE", "AIRCRAFT_META__EMERGENCY__EMERGENCY_NONE", 0 },
  { "EMERGENCY_GENERAL", "AIRCRAFT_META__EMERGENCY__EMERGENCY_GENERAL", 1 },
  { "EMERGENCY_LIFEGUARD", "AIRCRAFT_META__EMERGENCY__EMERGENCY_LIFEGUARD", 2 },
  { "EMERGENCY_MINFUEL", "AIRCRAFT_META__EMERGENCY__EMERGENCY_MINFUEL", 3 },
  { "EMERGENCY_NORDO", "AIRCRAFT_META__EMERGENCY__EMERGENCY_NORDO", 4 },
  { "EMERGENCY_UNLAWFUL", "AIRCRAFT_META__EMERGENCY__EMERGENCY_UNLAWFUL", 5 },
  { "EMERGENCY_DOWNED", "AIRCRAFT_META__EMERGENCY__EMERGENCY_DOWNED", 6 },
  { "EMERGENCY_RESERVED", "AIRCRAFT_META__EMERGENCY__EMERGENCY_RESERVED", 7 },
};
static const ProtobufCIntRange aircraft_meta__emergency__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex aircraft_meta__emergency__enum_values_by_name[8] =
{
  { "EMERGENCY_DOWNED", 6 },
  { "EMERGENCY_GENERAL", 1 },
  { "EMERGENCY_LIFEGUARD", 2 },
  { "EMERGENCY_MINFUEL", 3 },
  { "EMERGENCY_NONE", 0 },
  { "EMERGENCY_NORDO", 4 },
  { "EMERGENCY_RESERVED", 7 },
  { "EMERGENCY_UNLAWFUL", 5 },
};
const ProtobufCEnumDescriptor aircraft_meta__emergency__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AircraftMeta.Emergency",
  "Emergency",
  "AircraftMeta__Emergency",
  "",
  8,
  aircraft_meta__emergency__enum_values_by_number,
  8,
  aircraft_meta__emergency__enum_values_by_name,
  1,
  aircraft_meta__emergency__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aircraft_meta__sil_type__enum_values_by_number[4] =
{
  { "SIL_INVALID", "AIRCRAFT_META__SIL_TYPE__SIL_INVALID", 0 },
  { "SIL_UNKNOWN", "AIRCRAFT_META__SIL_TYPE__SIL_UNKNOWN", 1 },
  { "SIL_PER_SAMPLE", "AIRCRAFT_META__SIL_TYPE__SIL_PER_SAMPLE", 2 },
  { "SIL_PER_HOUR", "AIRCRAFT_META__SIL_TYPE__SIL_PER_HOUR", 3 },
};
static const ProtobufCIntRange aircraft_meta__sil_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex aircraft_meta__sil_type__enum_values_by_name[4] =
{
  { "SIL_INVALID", 0 },
  { "SIL_PER_HOUR", 3 },
  { "SIL_PER_SAMPLE", 2 },
  { "SIL_UNKNOWN", 1 },
};
const ProtobufCEnumDescriptor aircraft_meta__sil_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AircraftMeta.SilType",
  "SilType",
  "AircraftMeta__SilType",
  "",
  4,
  aircraft_meta__sil_type__enum_values_by_number,
  4,
  aircraft_meta__sil_type__enum_values_by_name,
  1,
  aircraft_meta__sil_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor aircraft_meta__field_descriptors[48] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flight",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, flight),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "squawk",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, squawk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alt_baro",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, alt_baro),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mag_heading",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, mag_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ias",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, ias),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, lon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messages",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, messages),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seen",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "air_ground",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, air_ground),
    &aircraft_meta__air_ground__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alt_geom",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, alt_geom),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baro_rate",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, baro_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geom_rate",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, geom_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gs",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, gs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tas",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, tas),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mach",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, mach),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "true_heading",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, true_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track",
    27,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, track),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track_rate",
    28,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, track_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roll",
    29,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_qnh",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nav_qnh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_altitude_mcp",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nav_altitude_mcp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_altitude_fms",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nav_altitude_fms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_heading",
    33,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nav_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nic",
    34,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rc",
    35,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, rc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    36,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nic_baro",
    37,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nic_baro),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nac_p",
    38,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nac_p),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nac_v",
    39,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nac_v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sil",
    40,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, sil),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seen_pos",
    41,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, seen_pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert",
    42,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, alert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spi",
    43,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, spi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gva",
    44,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, gva),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sda",
    45,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, sda),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "declination",
    46,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, declination),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wind_speed",
    47,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, wind_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wind_direction",
    48,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, wind_direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr_type",
    100,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, addr_type),
    &aircraft_meta__addr_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "emergency",
    101,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, emergency),
    &aircraft_meta__emergency__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sil_type",
    102,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, sil_type),
    &aircraft_meta__sil_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nav_modes",
    150,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, nav_modes),
    &aircraft_meta__nav_modes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valid_source",
    151,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AircraftMeta, valid_source),
    &aircraft_meta__valid_source__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aircraft_meta__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  43,   /* field[43] = addr_type */
  13,   /* field[13] = air_ground */
  36,   /* field[36] = alert */
  4,   /* field[4] = alt_baro */
  14,   /* field[14] = alt_geom */
  15,   /* field[15] = baro_rate */
  3,   /* field[3] = category */
  40,   /* field[40] = declination */
  12,   /* field[12] = distance */
  44,   /* field[44] = emergency */
  1,   /* field[1] = flight */
  16,   /* field[16] = geom_rate */
  17,   /* field[17] = gs */
  38,   /* field[38] = gva */
  6,   /* field[6] = ias */
  7,   /* field[7] = lat */
  8,   /* field[8] = lon */
  19,   /* field[19] = mach */
  5,   /* field[5] = mag_heading */
  9,   /* field[9] = messages */
  32,   /* field[32] = nac_p */
  33,   /* field[33] = nac_v */
  26,   /* field[26] = nav_altitude_fms */
  25,   /* field[25] = nav_altitude_mcp */
  27,   /* field[27] = nav_heading */
  46,   /* field[46] = nav_modes */
  24,   /* field[24] = nav_qnh */
  28,   /* field[28] = nic */
  31,   /* field[31] = nic_baro */
  29,   /* field[29] = rc */
  23,   /* field[23] = roll */
  11,   /* field[11] = rssi */
  39,   /* field[39] = sda */
  10,   /* field[10] = seen */
  35,   /* field[35] = seen_pos */
  34,   /* field[34] = sil */
  45,   /* field[45] = sil_type */
  37,   /* field[37] = spi */
  2,   /* field[2] = squawk */
  18,   /* field[18] = tas */
  21,   /* field[21] = track */
  22,   /* field[22] = track_rate */
  20,   /* field[20] = true_heading */
  47,   /* field[47] = valid_source */
  30,   /* field[30] = version */
  42,   /* field[42] = wind_direction */
  41,   /* field[41] = wind_speed */
};
static const ProtobufCIntRange aircraft_meta__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 15, 13 },
  { 20, 14 },
  { 100, 43 },
  { 150, 46 },
  { 0, 48 }
};
const ProtobufCMessageDescriptor aircraft_meta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AircraftMeta",
  "AircraftMeta",
  "AircraftMeta",
  "",
  sizeof(AircraftMeta),
  48,
  aircraft_meta__field_descriptors,
  aircraft_meta__field_indices_by_name,
  5,  aircraft_meta__number_ranges,
  (ProtobufCMessageInit) aircraft_meta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aircraft_history__field_descriptors[4] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AircraftHistory, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alt_baro",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AircraftHistory, alt_baro),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(AircraftHistory, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lon",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(AircraftHistory, lon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aircraft_history__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  1,   /* field[1] = alt_baro */
  2,   /* field[2] = lat */
  3,   /* field[3] = lon */
};
static const ProtobufCIntRange aircraft_history__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 5, 1 },
  { 8, 2 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor aircraft_history__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AircraftHistory",
  "AircraftHistory",
  "AircraftHistory",
  "",
  sizeof(AircraftHistory),
  4,
  aircraft_history__field_descriptors,
  aircraft_history__field_indices_by_name,
  3,  aircraft_history__number_ranges,
  (ProtobufCMessageInit) aircraft_history__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aircrafts_update__field_descriptors[4] =
{
  {
    "now",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(AircraftsUpdate, now),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messages",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(AircraftsUpdate, messages),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "history",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AircraftsUpdate, n_history),
    offsetof(AircraftsUpdate, history),
    &aircraft_history__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aircraft",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AircraftsUpdate, n_aircraft),
    offsetof(AircraftsUpdate, aircraft),
    &aircraft_meta__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aircrafts_update__field_indices_by_name[] = {
  3,   /* field[3] = aircraft */
  2,   /* field[2] = history */
  1,   /* field[1] = messages */
  0,   /* field[0] = now */
};
static const ProtobufCIntRange aircrafts_update__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 14, 2 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor aircrafts_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AircraftsUpdate",
  "AircraftsUpdate",
  "AircraftsUpdate",
  "",
  sizeof(AircraftsUpdate),
  4,
  aircrafts_update__field_descriptors,
  aircrafts_update__field_indices_by_name,
  2,  aircrafts_update__number_ranges,
  (ProtobufCMessageInit) aircrafts_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor receiver__field_descriptors[11] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Receiver, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refresh",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Receiver, refresh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Receiver, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Receiver, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Receiver, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "antenna_serial",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Receiver, antenna_serial),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "antenna_flags",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Receiver, antenna_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "antenna_gps_sats",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Receiver, antenna_gps_sats),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "antenna_gps_hdop",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Receiver, antenna_gps_hdop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "antenna_reserved",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Receiver, antenna_reserved),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "history",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Receiver, history),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned receiver__field_indices_by_name[] = {
  4,   /* field[4] = altitude */
  6,   /* field[6] = antenna_flags */
  8,   /* field[8] = antenna_gps_hdop */
  7,   /* field[7] = antenna_gps_sats */
  9,   /* field[9] = antenna_reserved */
  5,   /* field[5] = antenna_serial */
  10,   /* field[10] = history */
  2,   /* field[2] = latitude */
  3,   /* field[3] = longitude */
  1,   /* field[1] = refresh */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange receiver__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 14, 9 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor receiver__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Receiver",
  "Receiver",
  "Receiver",
  "",
  sizeof(Receiver),
  11,
  receiver__field_descriptors,
  receiver__field_indices_by_name,
  2,  receiver__number_ranges,
  (ProtobufCMessageInit) receiver__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor statistic_entry__field_descriptors[44] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, stop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messages",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, messages),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_distance_in_metres",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, max_distance_in_metres),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_distance_in_nautical_miles",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, max_distance_in_nautical_miles),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude_suppressed",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, altitude_suppressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tracks_new",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, tracks_new),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tracks_single_message",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, tracks_single_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tracks_with_position",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, tracks_with_position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tracks_mlat_position",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, tracks_mlat_position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tracks_tisb_position",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, tracks_tisb_position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_demod",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpu_demod),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_reader",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpu_reader),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_background",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpu_background),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_surface",
    40,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_surface),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_airborne",
    41,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_airborne),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_global_ok",
    42,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_global_ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_global_bad",
    43,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_global_bad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_global_range",
    44,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_global_range),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_global_speed",
    45,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_global_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_global_skipped",
    46,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_global_skipped),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_local_ok",
    47,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_local_ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_local_aircraft_relative",
    48,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_local_aircraft_relative),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_local_receiver_relative",
    49,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_local_receiver_relative),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_local_skipped",
    50,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_local_skipped),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_local_range",
    51,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_local_range),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_local_speed",
    52,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_local_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpr_filtered",
    53,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, cpr_filtered),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_modeac",
    70,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, remote_modeac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_modes",
    71,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, remote_modes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_bad",
    72,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, remote_bad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_unknown_icao",
    73,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, remote_unknown_icao),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_accepted",
    74,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, remote_accepted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_samples_processed",
    90,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_samples_processed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_samples_dropped",
    91,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_samples_dropped),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_modeac",
    92,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_modeac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_modes",
    93,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_modes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_bad",
    94,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_bad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_unknown_icao",
    95,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_unknown_icao),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_strong_signals",
    96,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_strong_signals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_signal",
    97,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_signal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_noise",
    98,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_noise),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_peak_signal",
    99,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_peak_signal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_accepted",
    100,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StatisticEntry, local_accepted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned statistic_entry__field_indices_by_name[] = {
  5,   /* field[5] = altitude_suppressed */
  15,   /* field[15] = cpr_airborne */
  27,   /* field[27] = cpr_filtered */
  17,   /* field[17] = cpr_global_bad */
  16,   /* field[16] = cpr_global_ok */
  18,   /* field[18] = cpr_global_range */
  20,   /* field[20] = cpr_global_skipped */
  19,   /* field[19] = cpr_global_speed */
  22,   /* field[22] = cpr_local_aircraft_relative */
  21,   /* field[21] = cpr_local_ok */
  25,   /* field[25] = cpr_local_range */
  23,   /* field[23] = cpr_local_receiver_relative */
  24,   /* field[24] = cpr_local_skipped */
  26,   /* field[26] = cpr_local_speed */
  14,   /* field[14] = cpr_surface */
  13,   /* field[13] = cpu_background */
  11,   /* field[11] = cpu_demod */
  12,   /* field[12] = cpu_reader */
  43,   /* field[43] = local_accepted */
  37,   /* field[37] = local_bad */
  35,   /* field[35] = local_modeac */
  36,   /* field[36] = local_modes */
  41,   /* field[41] = local_noise */
  42,   /* field[42] = local_peak_signal */
  34,   /* field[34] = local_samples_dropped */
  33,   /* field[33] = local_samples_processed */
  40,   /* field[40] = local_signal */
  39,   /* field[39] = local_strong_signals */
  38,   /* field[38] = local_unknown_icao */
  3,   /* field[3] = max_distance_in_metres */
  4,   /* field[4] = max_distance_in_nautical_miles */
  2,   /* field[2] = messages */
  32,   /* field[32] = remote_accepted */
  30,   /* field[30] = remote_bad */
  28,   /* field[28] = remote_modeac */
  29,   /* field[29] = remote_modes */
  31,   /* field[31] = remote_unknown_icao */
  0,   /* field[0] = start */
  1,   /* field[1] = stop */
  9,   /* field[9] = tracks_mlat_position */
  6,   /* field[6] = tracks_new */
  7,   /* field[7] = tracks_single_message */
  10,   /* field[10] = tracks_tisb_position */
  8,   /* field[8] = tracks_with_position */
};
static const ProtobufCIntRange statistic_entry__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 20, 11 },
  { 40, 14 },
  { 70, 28 },
  { 90, 33 },
  { 0, 44 }
};
const ProtobufCMessageDescriptor statistic_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatisticEntry",
  "StatisticEntry",
  "StatisticEntry",
  "",
  sizeof(StatisticEntry),
  44,
  statistic_entry__field_descriptors,
  statistic_entry__field_indices_by_name,
  5,  statistic_entry__number_ranges,
  (ProtobufCMessageInit) statistic_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor statistics__polar_range_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Statistics__PolarRangeEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Statistics__PolarRangeEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned statistics__polar_range_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange statistics__polar_range_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor statistics__polar_range_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Statistics.PolarRangeEntry",
  "PolarRangeEntry",
  "Statistics__PolarRangeEntry",
  "",
  sizeof(Statistics__PolarRangeEntry),
  2,
  statistics__polar_range_entry__field_descriptors,
  statistics__polar_range_entry__field_indices_by_name,
  1,  statistics__polar_range_entry__number_ranges,
  (ProtobufCMessageInit) statistics__polar_range_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor statistics__field_descriptors[6] =
{
  {
    "latest",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Statistics, latest),
    &statistic_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_1min",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Statistics, last_1min),
    &statistic_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_5min",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Statistics, last_5min),
    &statistic_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_15min",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Statistics, last_15min),
    &statistic_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Statistics, total),
    &statistic_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "polar_range",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Statistics, n_polar_range),
    offsetof(Statistics, polar_range),
    &statistics__polar_range_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned statistics__field_indices_by_name[] = {
  3,   /* field[3] = last_15min */
  1,   /* field[1] = last_1min */
  2,   /* field[2] = last_5min */
  0,   /* field[0] = latest */
  5,   /* field[5] = polar_range */
  4,   /* field[4] = total */
};
static const ProtobufCIntRange statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Statistics",
  "Statistics",
  "Statistics",
  "",
  sizeof(Statistics),
  6,
  statistics__field_descriptors,
  statistics__field_indices_by_name,
  1,  statistics__number_ranges,
  (ProtobufCMessageInit) statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
